[package]
name = "file-collector"
version = "0.2.3"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2021"
description = "CLI tool to collect files from multiple directories into a single target"
repository = "https://github.com/msfjarvis/file-collector"
homepage = "https://github.com/msfjarvis/file-collector"
license = "MIT/Apache-2.0"
keywords = []
readme = "README.md"
include = ["src/**/*", "LICENSE-*", "README.md"]
publish = false

[dependencies]
anyhow = "1.0.58"
dirs = "4.0.0"
futures = "0.3.21"
serde = "1.0.138"
serde_derive = "1.0.138"
tokio = { version = "1.19.2", features = ["tokio-macros"] }
toml = "0.5.9"
tracing = "0.1.35"
tracing-journald = { version = "0.3.0", optional = true }
tracing-subscriber = "0.3.14"
watchman_client = "0.8.0"

[dev-dependencies]
assay = "0.1.1"

[features]
journald = ["tracing-journald"]
